{
name: "GEO",
index: "world",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "", // world volume has no mother
type: "box",
size: [250000.0, 250000.0, 250000.0], // mm, half-length
//size: [5000.0, 5000.0, 5000.0], // mm, half-length
material: "water",
invisible: 1,
}
////////////////////////////////// Define detector properties.  ///////////////////////////////////
{
name: "GEO",
index: "detector",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "world",
type: "box",
size: [25000.0, 25000.0, 250000.0], // mm, half-length
//size: [5000.0, 5000.0, 5000.0], // mm, half-length
position: [0.0, 0.0, 0.0],
//rotation: [90.0, 0.0, 0.0],
material: "lake_water",
color: [0.2,0.2,0.2,0.1],
drawstyle: "solid"
}

{
  name: "GEO",
  index: "rock",
  valid_begin: [0, 0],
  valid_end: [0, 0],
  mother: "world",
  type: "box",
  // Half-lengths in mm [x, y, z]
  // x: from -22m to 22m -> 44m total -> 22000mm half-length
  // y: from -22m to -12m -> 10m total -> 5000mm half-length
  // z: from -20m to 90m -> 110m total -> 55000mm half-length
  size: [22000.0, 5000.0, 55000.0],
  // Center position in mm [x, y, z]
  // x: (-22m + 22m) / 2 = 0m -> 0mm
  // y: (-22m + -12m) / 2 = -17m -> -17000mm
  // z: (-20m + 90m) / 2 = 35m -> 35000mm
  //position: [0.0, -17000.0, 35000.0],
  position: [0.0, -12000.0, 35000.0],
  material: "rock",
  color: [0.5, 0.4, 0.3, 1.0], // A solid brownish-gray
  drawstyle: "solid"
}


{
name: "GEO",
index: "km3net_doms",
enable: 1,
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "pmtarray",
//end_idx:  3347, //idx of the last pmt
//end_idx:  31,
start_idx: 0, //idx of the first pmt
//pmt_model: "r14374",
//pmt_model: "r11065",
  //pmt_model: "r12199",
pmt_model: "r12199m",
mu_metal: 0,
mu_metal_material: "aluminum",
mu_metal_surface: "aluminum",
light_cone: 0,
pmt_detector_type: "idpmt",
sensitive_detector: "/mydet/pmt/inner",
efficiency_correction: 0.70000,
//pos_table: "DOMINFO_pen_small_equalx", //generated by positions.nb
//pos_table: "DOMINFO_pen_small",
//pos_table: "DOMINFO_pen_small_short",
//pos_table: "DOMINFO_aframe_spacing5m_box_forwardfacing",
pos_table: "DOMINFO_aframe_spacing5m_box",
orientation: "manual",
color: [0.3,0.5, 0.0, 0.7],
}



{
name: "GEO",
index: "rod_0",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 0.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_1",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 0.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_2",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 0.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_3",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 0.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_4",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 0.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_5",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 0.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_6",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 0.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_7",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 2600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_8",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 2600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_9",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 2600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_10",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 2600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_11",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 2600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_12",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 2600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_13",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 2600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_14",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 5200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_15",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 5200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_16",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 5200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_17",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 5200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_18",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 5200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_19",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 5200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_20",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 5200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_21",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 10200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_22",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 10200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_23",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 10200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_24",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 10200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_25",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 10200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_26",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 10200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_27",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 10200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_28",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 12800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_29",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 12800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_30",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 12800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_31",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 12800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_32",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 12800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_33",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 12800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_34",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 12800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_35",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 15400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_36",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 15400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_37",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 15400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_38",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 15400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_39",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 15400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_40",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 15400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_41",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 15400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_42",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 20400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_43",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 20400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_44",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 20400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_45",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 20400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_46",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 20400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_47",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 20400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_48",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 20400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_49",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 23000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_50",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 23000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_51",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 23000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_52",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 23000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_53",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 23000.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_54",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 23000.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_55",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 23000.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_56",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 25600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_57",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 25600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_58",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 25600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_59",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 25600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_60",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 25600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_61",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 25600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_62",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 25600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_63",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 30600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_64",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 30600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_65",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 30600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_66",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 30600.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_67",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 30600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_68",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 30600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_69",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 30600.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_70",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 33200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_71",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 33200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_72",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 33200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_73",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 33200.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_74",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 33200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_75",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 33200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_76",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 33200.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_77",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 35800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_78",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 35800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_79",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 35800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_80",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 35800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_81",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 35800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_82",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 35800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_83",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 35800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_84",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 40800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_85",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 40800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_86",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 40800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_87",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 40800.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_88",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 40800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_89",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 40800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_90",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 40800.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_91",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 43400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_92",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 43400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_93",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 43400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_94",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 43400.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_95",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 43400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_96",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 43400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_97",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 43400.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_98",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, -1500.0, 46000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_99",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, -1500.0, 46000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_100",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [-2000.0, 1500.0, 46000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_101",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1650.0,
position: [2000.0, 1500.0, 46000.0],
rotation: [0, 90, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_102",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [-4000.0, 0.0, 46000.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_103",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [0.0, 0.0, 46000.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_104",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 1150.0,
position: [4000.0, 0.0, 46000.0],
rotation: [90, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}


{
name: "GEO",
index: "rod_105",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 1300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_106",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 3900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_107",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 11500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_108",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 14100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_109",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 21700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_110",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 24300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_111",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 31900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_112",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 34500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_113",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 42100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_114",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, -1500.0, 44700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_115",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 1300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_116",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 3900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_117",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 11500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_118",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 14100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_119",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 21700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_120",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 24300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_121",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 31900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_122",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 34500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_123",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 42100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_124",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, -1500.0, 44700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_125",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 1300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_126",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 3900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_127",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 11500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_128",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 14100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_129",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 21700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_130",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 24300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_131",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 31900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_132",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 34500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_133",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 42100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_134",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, -1500.0, 44700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_135",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 1300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_136",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 3900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_137",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 11500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_138",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 14100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_139",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 21700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_140",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 24300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_141",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 31900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_142",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 34500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_143",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 42100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_144",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [-4000.0, 1500.0, 44700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_145",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 1300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_146",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 3900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_147",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 11500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_148",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 14100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_149",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 21700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_150",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 24300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_151",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 31900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_152",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 34500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_153",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 42100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_154",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [0.0, 1500.0, 44700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_155",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 1300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_156",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 3900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_157",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 11500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_158",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 14100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_159",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 21700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_160",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 24300.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_161",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 31900.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_162",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 34500.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_163",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 42100.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}

{
name: "GEO",
index: "rod_164",
valid_begin: [0, 0],
valid_end: [0, 0],
mother: "detector",
type: "tube",
r_min: 0,
r_max: 100,
size_z: 950.0,
position: [4000.0, 1500.0, 44700.0],
rotation: [0, 0, 0],
material: "stainless_steel",
color: [0.8, 0.8, 0.8, 1.0],
drawstyle: "solid"
}
