# Streaming frame ambient light test
/rat/db/set DETECTOR experiment "End"
/rat/db/set DETECTOR geo_file "End/END.geo"
/rat/db/set GEO[km3net_doms] pmt_model "r11780_hqe"
/rat/db/load End/ENDNTUPLE.ratdb
/rat/db/set ENDNTUPLE save_discrete_signal false
/rat/db/set GEO[km3net_doms] start_idx  0
/rat/db/set GEO[km3net_doms] end_idx  1

/rat/db/set IO[NtupleProc] include_frame_info true
/rat/db/set IO[NtupleProc] include_frame_ambient true


/rat/proc streamingdaq
/rat/proc streamingframe
/rat/procset frame_window_length_ms 100.0

/rat/proc ambientlight
/rat/procset rate 7000.0

/rat/proclast outntuple
/rat/procset file "output_ambient_light.root"

/generator/add combo pbomb:point:poisson
/generator/pos/set 0.0 0.0 0.0
/generator/vtx/set 0 400      # 0 photons, 400nm wavelength
/generator/rate/set 1.0       # Poisson rate to keep time generator valid

# Dummy generator (0 photons) to satisfy Geant4
/run/initialize
/run/beamOn 20000
