# Set the detector
/rat/db/set DETECTOR experiment "End"
/rat/db/set DETECTOR geo_file "End/END.geo"
/rat/db/load End/SAMPLER.ratdb
/rat/db/load End/ENDDAQ.ratdb
/rat/db/load End/ENDDIGITIZER_ANALYSIS.ratdb
/rat/db/load End/ENDNTUPLE.ratdb
/rat/db/load End/ENDPMTPULSE.ratdb

# Initialize the run
/run/initialize

# DAQ and waveform analysis
/rat/proc endforcedtrigger
/rat/proc WaveformPrep
/rat/procset analyzer_name "simpleanalyzer"

# Set the output file
/rat/proclast endntuple
/rat/procset file "muon_1gev_output.root"

/generator/add combo gun:point:poisson
# Generate a 1 GeV muon at (0,0,0) along +z
/generator/vtx/set mu- 0 0 1 1000
/generator/pos/set 0 0 0

# Run 10 events
/run/beamOn 5
